/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=workers/location-retention/wrangler.jsonc --include-runtime=false workers/location-retention/worker-configuration.d.ts` (hash: 87f15fa96ef67cd07985d29399347bf0)
interface __BaseEnv_Env {
	LOCATION_DB: D1Database;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
