import { createHash } from "node:crypto";
import { mkdir, readdir, readFile, rm, writeFile } from "node:fs/promises";
import path from "node:path";
import nextEnv from "@next/env";

nextEnv.loadEnvConfig(process.cwd());
const { analytics, analyticsCsp } = await import("../src/lib/analytics-config.ts");
const { locationAnalyticsEnabled } = await import("../src/lib/location-config.ts");
const { publishedPaths } = await import("../src/lib/public-paths.generated.ts");

const headersPath = path.resolve("out", "_headers");
const headersTemplate = await readFile(headersPath, "utf8");
const hosts = analyticsCsp(analytics);
if (!headersTemplate.includes("__ANALYTICS_SCRIPT_SRC__") || !headersTemplate.includes("__ANALYTICS_CONNECT_SRC__")) {
  throw new Error("Missing analytics CSP placeholders");
}
await writeFile(headersPath, headersTemplate
  .replaceAll("__ANALYTICS_SCRIPT_SRC__", hosts.script)
  .replaceAll("__ANALYTICS_CONNECT_SRC__", hosts.connect));

// Admin documents live only in the Functions bundle, never Pages' public
// asset fallback (including when the platform exhausts its Functions quota).
const root = path.resolve("out", "admin");
const assets = {};
async function collect(directory) {
  for (const entry of await readdir(directory, { withFileTypes: true })) {
    const file = path.join(directory, entry.name);
    if (entry.isDirectory()) {
      await collect(file);
      continue;
    }
    const content = await readFile(file, "utf8");
    const url = `/admin/${path.relative(root, file).split(path.sep).join("/")}`;
    const hashes = [...content.matchAll(/<script\b[^>]*>([\s\S]*?)<\/script>/g)]
      .filter((match) => match[1])
      .map((match) => `'sha256-${createHash("sha256").update(match[1]).digest("base64")}'`);
    assets[url] = {
      content,
      contentType: file.endsWith(".html") ? "text/html; charset=utf-8" : "text/plain; charset=utf-8",
      scriptHashes: [...new Set(hashes)].join(" "),
    };
  }
}
await collect(root);
if (!assets["/admin/analytics/index.html"]) throw new Error("Missing private analytics export");
const publicPaths = [];
async function collectPublic(directory) {
  for (const entry of await readdir(directory, { withFileTypes: true })) {
    if (entry.name === "admin" || entry.name === "_next") continue;
    const file = path.join(directory, entry.name);
    if (entry.isDirectory()) await collectPublic(file);
    else if (entry.name === "index.html") {
      const relative = path.relative(path.resolve("out"), directory).split(path.sep).join("/");
      publicPaths.push(relative ? `/${relative}/` : "/");
    }
  }
}
await collectPublic(path.resolve("out"));
if (JSON.stringify(publicPaths.filter((url) => !["/404/", "/_not-found/"].includes(url)).sort()) !== JSON.stringify(publishedPaths)) {
  throw new Error("Published pages differ from the client location allowlist.");
}
await mkdir(path.resolve("server", "analytics"), { recursive: true });
await writeFile(
  path.resolve("server", "analytics", "admin-assets.generated.ts"),
  `// Generated by scripts/package-admin.mjs. Generic UI only.\nexport const adminAssets: Record<string, { content: string; contentType: string; scriptHashes: string }> = ${JSON.stringify(assets)};\nexport const publicPaths: string[] = ${JSON.stringify(publicPaths)};\n`,
);
await rm(root, { recursive: true });
console.log(`Packaged ${Object.keys(assets).length} private admin documents into Functions; removed public copies. Analytics provider: ${analytics.provider}. Location collection: ${locationAnalyticsEnabled}.`);
